### ISSUE TITLE
How to get the id ?

### ISSUE THREAD

**Issue by yesnault** [mathieuancelin/play2-couchbase#8]
With this beer

```
package models
import play.api.libs.json._

case class Beer(id: String, name: String, brewery_id: String, style: String)

object Beers {
  implicit val fmt = Json.format[Beer]
}
```

I've got this error :

```
[RuntimeException: Document does not match object]
```

With

```
case class Beer(name: String, brewery_id: String, style: String)
```

No error, but how to get the id (couchbase meta.id) ?

Thanks a lot !

**Comment by mathieuancelin** [comment]
Hi,

I guess you're using the CRUD module here.

by default, the CRUD module add a generated '_id' field in your JSON data structure and this field will be the couchbase key. Each HTTP operation send the generated ID back so you can query your objects. Your can customize the name of the field with : 

``` scala
object BeerController extends CouchbaseCrudSourceController[Beer] {
  val bucket = Couchbase.bucket("default")
  res.ID = "id"
}
```

if your case class contains a field named id, then the module will use the value provided as couchbase key.
You can also add an "_id" field in your case class. It will be the couchbase key

**Comment by yesnault** [comment]
Hi,

Thanks for the reply.

Yes, it's the CRUD module, it's not working with res.ID = "id", the field id is always empty

The files : 
BeerController.scala

```
package controllers

import org.ancelin.play2.couchbase.crud.CouchbaseCrudSourceController
import models.Beer
import org.ancelin.play2.couchbase.Couchbase
import play.api.Play.current

import models.Beers.fmt

object BeersController extends CouchbaseCrudSourceController[Beer] {

  val bucket = Couchbase.bucket("beer-sample")
  res.ID = "id"
  override val defaultViewName = "by_name"
  override val defaultDesignDocname = "beer"
}
```

Beer.scala

```
package models

import play.api.libs.json._

case class Beer(name: String, brewery_id: String, style: String)

object Beers {
  implicit val fmt = Json.format[Beer]
}

```

Couchbase view : 

```
function (doc, meta) {
  if(doc.type && doc.style && doc.type == "beer") {
    emit(doc);
  }
}
```

Json Return from couchbase (first element)

```
{"total_rows":4423,"rows":[
{"id":"sullivan_s_black_forest_brew_haus_grill-38_special_bitter","key":{"name":".38 Special Bitter","abv":3.8,"ibu":0,"srm":0,"upc":0,"type":"beer","brewery_id":"sullivan_s_black_forest_brew_haus_grill","updated":"2010-07-22 20:00:20","description":"Don't let the name scare you, this is an easy drinker, slightly sweet and bitter.","style":"Ordinary Bitter","category":"British Ale"},"value":null},
```

First Element of Json return from BeerController : 

```
[{"name":".38 Special Bitter","brewery_id":"sullivan_s_black_forest_brew_haus_grill","style":"Ordinary Bitter","id":""},
```

--> The field id is always empty. I probably missed something.

with id: String in class Beer, I've got this error : [RuntimeException: Document does not match object]

I use Play Framework 2.2.0-RC1.

**Comment by mathieuancelin** [comment]
Ok,

I think I know what's happening.

The CRUD module is trying to read the couchbase id from within the document (because here I assumed that data is injected that way). But it's obvious that the couchbase beers bucket doesn't follow this philosophy :-)

So, I'm not sure if it's a bug, but there is definitely something missing here.

I'll try to expose a new find API that will return a tuple of (Document, Id) extracted from the ViewRows, and use it inside the CRUD module (if the id is not found inside the document, or something like that)

However you can try the CRUD module starting from an empty bucket, it work like a charm (I hope ;-) )

**Comment by mathieuancelin** [comment]
I've just update the library.

Can you try again with a case class like : 

``` scala
case class Beer(name: String, brewery_id: String, style: String)
```

a find should return 

``` json
{"name":"thename", "brewery_id":"theid", "style":"thestyle", "_id":"theactualcouchbaseid"}
```

without the validation error

**Comment by yesnault** [comment]
Yes, it works !

With id:String in class Beer, there is validation error. Could you map the id on attribute ?

**Comment by mathieuancelin** [comment]
Yes I know, but I'm not sure it's a good idea to do that.

The binding to produce a Beer instance is done through a Reads[Beer] reading the original document in Couchbase. As this document doesn't contains the id, the Reads[Beer] fails to produce an instance of Beer with an 'id' field.

If I merge the Id inside the original document before binding, it could leads to confusion because it means that you can't trust the data inside your bucket (and that's actually the case because this bucket is just a sample bucket provided by couchbase) and that's the whole point of using typesafe models instead of using JsObject as model.

I'll try to think about something here, but I'm convinced that if you want to bind your data on a case class like : 

``` scala
case class Beer(name: String, brewery_id: String, style: String, id: String)
```

you have to add this id inside every document of your bucket. Adding the "id" field inside REST responses is just an helpful feature of the CRUD module

**Comment by mathieuancelin** [comment]
I've just updated the library and the CRUD module.

Now you can do something like : 

``` scala
object ShortURLController extends CouchbaseCrudSourceController[ShortURL] {
  val bucket = Couchbase.bucket("default")
  override def defaultViewName = "by_url"
  override def defaultDesignDocname = "shorturls"
  override def idKey = "__myAwesomeIdKey"
}
```

**Comment by damageco** [comment]
Hi,

I've got similar problem, but first on creation of documents in Couchbase. With this ShortURLController, when I try to post a document this curl, like this : 
<code>curl -X POST -d '{ "originalUrl":"http://www.france2.com", "t":"shorturl" }' --header "Content-Type:application/json" http://localhost:9000/urls --include</code>
I've got this reply :
<code>HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Content-Length: 60
{"obj.id":[{"msg":"validate.error.missing-path","args":[]}]}
</code>
It's seems that the JSON validator is expecting a value that will be generated in many cases...

PS: Thanks for this great job !

**Comment by mathieuancelin** [comment]
Hi,

thanks for the kind words.

The case of the `ShortURLController` is different because the `ShortUrl` model is like 

``` scala
case class ShortURL(id: String, originalUrl: String, t: String = "shorturl")
```

it explicitly needs an `id` field, so you actually have to pass an id to create a short URL.

play2-couchbase CRUD module works like that : 
- Read the POST body to extract a ShortUrl instance, if the structure doesn't match, then you've got an error
- search for an `_id` field in the document (`_id` or whatever you defined in the controller, in your case it's `id`)
  - if there is no `_id` in the Scala model, then play2-couchbase generates one for you because couchbase needs a key, and merges it with your actual JSON document 
  - if there is one `_id` field, then it's value is used as couchbase key
- insert the `key : jsondoc`tuple in couchbase

If you don't want to manager ids in ShortUrls, just define it like 

``` scala
case class ShortURL(originalUrl: String, t: String = "shorturl")
```

Hope it helps

**Comment by damageco** [comment]
Ok, but if I not define the id field in the class how wil I be able to fetch ShortURL with technical ID ? Or update an existing ShortURL document in CouchBase ?

**Comment by mathieuancelin** [comment]
If you don't specify an `_id` field, play2-couchbase will generate one for you, include it in the JSON documen, use it as couchbase key and sent it back to you so you can use it to retrieve your object : 

if you do 

`curl -X POST -d '{ "originalUrl":"http://www.google.fr", "t":"shorturl" }' --header "Content-Type:application/json" http://localhost:9000/urls --include`

it will become in play2-couchbase

``` scala
ShortURL("http://www.google.fr", "shorturl")
```

it will become in couchbase (with key `876-8765-EF56-986`) 

``` json
{
  "_id":"876-8765-EF56-986",
  "t": "shorturl",
  "originalUrl": "http://www.google.fr"
}
```

and the HTTP response will be 

``` json
{"id":"876-8765-EF56-986"}
```
